### PR TITLE
[date-picker] date range keyboard

### LINKED ISSUE #995: DateRangePicker - disabled dates should not be available from the keyboard
**Describe the bug**
Disabled dates should not be  available from the keyboard. 

**Code example**
Open [codesandbox](https://codesandbox.io/p/sandbox/sad-germain-np5rm2?file=%2Fsrc%2FApp.tsx%3A23%2C45) and see the video https://github.com/semrush/intergalactic/assets/142894895/68c3dcee-f728-46e9-bcc0-83ddf1796956

**To Reproduce**
1. Open sandbox
2. Open dateRangePicker
3. Navigate through the dates with the arrows.
4. Select any date that has a disabled state

**Expected behavior**
Disabled dates should not be selectable

**Additional context**
Also, the months don't change when i go outside the current period. https://github.com/semrush/intergalactic/assets/142894895/a5fa9974-12c3-4576-9acf-f569c58024f9

### PR DESCRIPTION
**Pull request by ilyabrower**
## Motivation and Context
Fixes #995 

## How has this been tested?
I have added unit tests and tested it manually

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Nice improve.

## Checklist:

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly or it's not required.
- [X] Unit tests are not broken.
- [X] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [X] I have added new unit tests on added of fixed functionality.

### CODE REVIEW

File: semcore/date-picker/src/components/RangePickerAbstract.jsx [hunk 1]
```diff
@@ -102,25 +103,34 @@ class RangePickerAbstract extends Component {
...
-        const month_right_period = right_period.getMonth();
-        const month_displayed_Period = displayedPeriod.getMonth();
-        if (month_right_period - month_displayed_Period > 1) {
-          return RangePickerAbstract.subtract(right_period, 1, 'month');
-        } else if (month_right_period - month_displayed_Period < 0) {
-          return right_period;
+      const [left_period, right_period] = next_highlighted;
+
+      const monthDisplayedPeriod = displayedPeriod?.getMonth();
+      const monthPeriod = right_period || left_period;
```
Comment (msereniti) [inline semcore/date-picker/src/components/RangePickerAbstract.jsx:112]: I understand that `left_period` corresponds to date of the highlighted period start, while `right_period` for the end. What `monthPeriod` means in this context? And why are making such a fallback?

File: semcore/date-picker/src/DateRangePicker.jsx [hunk 2]
```diff
@@ -32,10 +32,10 @@ class DateRangePickerRoot extends RangePickerAbstract {
   navigateStep = 'month';
   keyStep = 'day';
   keyDiff = {
-    37: -1,
-    38: -7,
-    39: 1,
-    40: 7,
+    ArrowLeft: -1,
```
Comment (msereniti) [inline semcore/date-picker/src/DateRangePicker.jsx:35]: It should have been done a long time ago, but looks like you forgot about adding a same change to `DatePickerAbstract`

File: semcore/date-picker/src/components/RangePickerAbstract.jsx (hunk 1 above)
Comment (ilyabrower) [reply semcore/date-picker/src/components/RangePickerAbstract.jsx:112]: renamed to `period`. 

Fallback - for move calendar if we try to select first point of period.

**Review by msereniti — APPROVED** [review]
